### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by MartinHylleberg** [scandihealth/lpr3-docs#46] opened 2018-02-22 14:58 UTC
We have tried calling the service with the SoapUI example project that you gave us. This worked fine :)

In order to start a parallel validation of our CDA documents we tried switching the CDA document from your example with our own.

This gave the following error:
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/>
   <soap:Body>
      <soap:Fault>
         <faultcode>soap:Server</faultcode>
         <faultstring>Internal server error</faultstring>
         <detail>
            <medcom:FaultCode xmlns:medcom="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">processing_problem</medcom:FaultCode>
         </detail>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>

We have tried switching back to your supplied project and now we get the above error all the time.

I have attached the modified project to this issue.

[lpr3_sse.zip](https://github.com/scandihealth/lpr3-docs/files/1748360/lpr3_sse.zip)

**Comment by cjonigkeit-csc** [comment] 2018-02-22 15:16
The error is caused by an expired assertion:

```
16:09:43,779 ERROR [com.dxc.lpr.cda.ws.interceptors.CDAWebServiceInterceptor] (default task-25)
    Error processing CDA: com.dxc.lpr.security.exception.SecurityValidationException:
        ID kortet er udløbet:  Thu Feb 22 14:45:36 CET 2018
```

We will look into why the _generic_ error code is returned.

**Comment by jkiddo** [comment] 2018-02-23 12:10
FYI - this might just be related to the console output but the timezone differ between what is received from Systematic (Z) and the console log (CET)

**Comment by jonigkeit** [comment] 2018-02-23 13:32
Nope 2018-02-22T13:45:36Z is precisely 2018-02-22T14:45:36CET. CET is +01:00

**Comment by jonigkeit** [comment] 2018-02-23 13:33
Thet are the same Instant in time

**Comment by jkiddo** [comment] 2018-02-23 13:53
Correcto - my former sergent had another definition of Z time

**Comment by cjonigkeit-csc** [comment] 2018-02-23 19:53
@MartinHylleberg if you have no further comments to this issue, feel free to close it.

**Closed** 2018-02-26 07:26 UTC
Labels: help wanted
