### ISSUE TITLE
java.lang.NullPointerException again again

### ISSUE THREAD

**Issue by JacobBangSSE** [scandihealth/lpr3-docs#72] opened 2018-03-23 09:40 UTC
Sorry the titles on our issues cannot be more specific but as long we just gets a generic NullPointerException it is diffecult for us to be more specific.

After some corrections after #71 we got another NullPointerException:
```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <env:Header xmlns:env="http://www.w3.org/2003/05/soap-envelope"/>
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">java.lang.NullPointerException</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

We are sending the following Envelope and CDA document:
[Envelope.zip](https://github.com/scandihealth/lpr3-docs/files/1840957/Envelope.zip)
[1521472645299@example.zip](https://github.com/scandihealth/lpr3-docs/files/1840941/1521472645299.example.zip)

As last time, we have validated the CDA document against the Schematron rules defined in:
https://github.com/scandihealth/lpr3-cda/blob/unstable/schematron.unstable.zip

And used the Medcom CDA validation web service provided in #70. Both of them returns zero errors and/or warnings:
```json
{"infos":[],"warnings":[],"errors":[]}
```

**Comment by jkiddo** [comment] 2018-04-03 14:39
Calling the service @ https://lprws-test.sds.dsdn.dk/cda-ws/DocumentRepository_Service/PatientHealthcareValidateReportingService

returns the following error:

```xml
<soap:Envelope
	xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header>
		<ns10:Header
			xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0"
			xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd"
			xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd"
			xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
			xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0"
			xmlns:ns4="urn:ihe:iti:xds-b:2007"
			xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
			xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
			xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion"
			xmlns:ns8="http://www.w3.org/2000/09/xmldsig#"
			xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
			<ns10:SecurityLevel>3</ns10:SecurityLevel>
			<ns10:Linking>
				<ns10:MessageID>AAABYovtAWFYi98mxbSpHlNPU0k=</ns10:MessageID>
			</ns10:Linking>
			<ns10:FlowStatus>flow_finalized_succesfully</ns10:FlowStatus>
			<ns10:RequireNonRepudiationReceipt>no</ns10:RequireNonRepudiationReceipt>
		</ns10:Header>
	</soap:Header>
	<soap:Body>
		<ns2:RegistryResponse
			xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0"
			xmlns:ns10="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd"
			xmlns:ns11="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd"
			xmlns:ns2="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
			xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0"
			xmlns:ns4="urn:ihe:iti:xds-b:2007"
			xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
			xmlns:ns6="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
			xmlns:ns7="urn:oasis:names:tc:SAML:2.0:assertion"
			xmlns:ns8="http://www.w3.org/2000/09/xmldsig#"
			xmlns:ns9="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
			status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
			<ns2:RegistryErrorList
				highestSeverity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning">
				<ns2:RegistryError
					codeContext="INTEGRITY_CHECK|||CUSTODIAN_NOT_FOUND|||Author/custodian is not matching registered relation"
					errorCode="InvalidDocumentContent"
					location="C1DEE9F6-EF9D-452D-A4B3-EC358F550826^7cb8dde4-8a2b-43f4-978b-0c92c7b2023a|||/*[local-name()='ClinicalDocument']/*[local-name()='custodian']/*[local-name()='assignedCustodian']/*[local-name()='representedCustodianOrganization']/*[local-name()='id']/@extension"
					severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Warning"></ns2:RegistryError>
			</ns2:RegistryErrorList>
		</ns2:RegistryResponse>
	</soap:Body>
</soap:Envelope>
```

It is caused by the mismatch between **ClinicalDocument/author/assignedAuthor/representedOrganization/id/extension**
 and 
**ClinicalDocument/custodian/assignedCustodian/representedCustodianOrganization/id/extension**

**Comment by RasmusThernoe** [comment] 2018-04-04 14:58
On the 23th of March our message passed both the LPR3 Schematron rules and the MedCom CDA validation - as stated above by Jacob.

Have you introduced additional validation rules since the 23th of March?

If so - which rules have been introduced?

Reporters might have to go back and reimplement existing functionality.

**Comment by jkiddo** [comment] 2018-04-05 07:41
The document you are sending still passes the schematron validation algorithms and CDA R2 validation from MedCom.

In your document ClinicalDocument/author/assignedAuthor/representedOrganization/id/extension has the value of 6081000016005 which is the SOR code of Region Midtjylland

ClinicalDocument/custodian/assignedCustodian/representedCustodianOrganization/id/extension has the value of 25469364 which is the CVR number of DXC (CSC Scandihealth).

Changing the CVR number to 78834412 (Systematic) should make your problems go away.

**Comment by jonigkeit** [comment] 2018-04-09 09:42
@JacobBangSSE if you have no further comment please close this issue.

**Closed** 2018-04-09 13:57 UTC
Labels: help wanted
