### ISSUE TITLE
Error parsing custodian id (CVR number) as integer

### ISSUE THREAD

**Issue by VassKi** [scandihealth/lpr3-docs#97] opened 2018-04-24 05:06 UTC
We are getting the following error:

> **java.lang.RuntimeException: Call failed on the server. Error has been logged to the server log and database: Error parsing custodian id (CVR number) as integer**

What does this error mean? Is this error coming from the CDA or the message?

Here is our request:
```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Header>
		<Security xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
			<Timestamp xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
				<Created>2018-04-23T06:59:32+02:00</Created>
			</Timestamp>
			<saml:Assertion IssueInstant="2018-04-23T04:54:32Z" Version="2.0" id="IDCard" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
				<saml:Issuer>TEST2-NSP-STS</saml:Issuer>
				<saml:Subject>
					<saml:NameID Format="medcom:cvrnumber">29190623</saml:NameID>
					<saml:SubjectConfirmation>
						<saml:ConfirmationMethod>urn:oasis:names:tc:SAML:2.0:cm:holder-of-key</saml:ConfirmationMethod>
						<saml:SubjectConfirmationData>
							<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
								<ds:KeyName>OCESSignature</ds:KeyName>
							</ds:KeyInfo>
						</saml:SubjectConfirmationData>
					</saml:SubjectConfirmation>
				</saml:Subject>
				<saml:Conditions NotBefore="2018-04-23T04:54:32Z" NotOnOrAfter="2018-04-24T04:54:32Z" />
				<saml:AttributeStatement id="IDCardData">
					<saml:Attribute Name="sosi:IDCardID">
						<saml:AttributeValue>fFjvVvk1ydpWuo9dZ29a1Q==</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="sosi:IDCardVersion">
						<saml:AttributeValue>1.0.1</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="sosi:IDCardType">
						<saml:AttributeValue>system</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="sosi:AuthenticationLevel">
						<saml:AttributeValue>3</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="sosi:OCESCertHash">
						<saml:AttributeValue>My0pBm7fVCtGMdDKcqnZhMG/VPk=</saml:AttributeValue>
					</saml:Attribute>
				</saml:AttributeStatement>
				<saml:AttributeStatement id="SystemLog">
					<saml:Attribute Name="medcom:ITSystemName">
						<saml:AttributeValue>Epic</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="medcom:CareProviderID" NameFormat="medcom:cvrnumber">
						<saml:AttributeValue>29190623</saml:AttributeValue>
					</saml:Attribute>
					<saml:Attribute Name="medcom:CareProviderName">
						<saml:AttributeValue>SundhedsPlatformen</saml:AttributeValue>
					</saml:Attribute>
				</saml:AttributeStatement>
				<ds:Signature id="OCESSignature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
					<ds:SignedInfo>
						<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
						<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
						<ds:Reference URI="#IDCard">
							<ds:Transforms>
								<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
								<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
							</ds:Transforms>
							<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
							<ds:DigestValue>9+8ogSSmOFgdJXH6lEWDmLbPwGA=</ds:DigestValue>
						</ds:Reference>
					</ds:SignedInfo>
					<ds:SignatureValue>Qd2v2wwluIM07mVNkiX5g44aLNIkN/F6kyNGwaILfL3yVp+B301oW+DjcAfuIBUX60o390HO8AMuaK+uiBdMjET6Fl47Ku7BnFlWiO4WhhHZoGYASSXmOAH+Ri6bd1kAc44dzcl7+/VflFVPRMwSEVvC/abUR2KWFHbEpnCeR1AJ3WY6meAUG5R8OxSAA/vbaFG6Fa8XPOglvcs2eD51467BQoqkTjzQhwAaysbp4uw1NSzafuB+EV3MJ81403eDSsqwfXQzdy8t1XBbSZdPtHhGfMSynxSgCtsKBekA1uhsjtL3UR18SV0sMQ4R+EGumhuqCz1JkOb/lew9LSMG1Q==</ds:SignatureValue>
					<ds:KeyInfo>
						<ds:X509Data>
							<ds:X509Certificate>MIIGJjCCBQ6gAwIBAgIEVp5mfDANBgkqhkiG9w0BAQsFADBHMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MSQwIgYDVQQDDBtUUlVTVDI0MDggU3lzdGVtdGVzdCBYSVggQ0EwHhcNMTYwNTA0MDg1NTAwWhcNMTkwNTA0MDg1NDAxWjCBlDELMAkGA1UEBhMCREsxLjAsBgNVBAoMJVN1bmRoZWRzZGF0YXN0eXJlbHNlbiAvLyBDVlI6MzMyNTc4NzIxVTAgBgNVBAUTGUNWUjozMzI1Nzg3Mi1GSUQ6NzY3OTQ4ODQwMQYDVQQDDCpTT1NJIFRlc3QgRmVkZXJhdGlvbiAoZnVua3Rpb25zY2VydGlmaWthdCkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCQipkwYq5Ncc68/6/ACLJK1k/I7wTMNq0lho7NvnGWGNAJkblmRksq6meGEGYgw5ZdvDqwsudKE+mU7YjZZ+EqW9HgceYYeoEObwR81r0/tAIbDTN2kLA8L2ZautRXI4+kq/+8tvqTwfCZjfx6AmbeL1Ky7npMlGZoluc5YjTR7bsJACr/caSzE6rf8bEFiJappjTCtIBQlQDuwGVUWjRU37SAr3mGlzgH7DnaVOJoBrjHW0OuPSm8mVImdym3sKlNleX8jiBhsvfaXl720aISg+dkVU4iEsXphlckV8GxQKfqNMuqGg2itLEEhJitBCrHYMlRtMx/kVtXJk/saMQjAgMBAAGjggLKMIICxjAOBgNVHQ8BAf8EBAMCA7gwgZcGCCsGAQUFBwEBBIGKMIGHMDwGCCsGAQUFBzABhjBodHRwOi8vb2NzcC5zeXN0ZW10ZXN0MTkudHJ1c3QyNDA4LmNvbS9yZXNwb25kZXIwRwYIKwYBBQUHMAKGO2h0dHA6Ly9mLmFpYS5zeXN0ZW10ZXN0MTkudHJ1c3QyNDA4LmNvbS9zeXN0ZW10ZXN0MTktY2EuY2VyMIIBIAYDVR0gBIIBFzCCARMwggEPBg0rBgEEAYH0UQIEBgQCMIH9MC8GCCsGAQUFBwIBFiNodHRwOi8vd3d3LnRydXN0MjQwOC5jb20vcmVwb3NpdG9yeTCByQYIKwYBBQUHAgIwgbwwDBYFRGFuSUQwAwIBARqBq0RhbklEIHRlc3QgY2VydGlmaWthdGVyIGZyYSBkZW5uZSBDQSB1ZHN0ZWRlcyB1bmRlciBPSUQgMS4zLjYuMS40LjEuMzEzMTMuMi40LjYuNC4yLiBEYW5JRCB0ZXN0IGNlcnRpZmljYXRlcyBmcm9tIHRoaXMgQ0EgYXJlIGlzc3VlZCB1bmRlciBPSUQgMS4zLjYuMS40LjEuMzEzMTMuMi40LjYuNC4yLjCBqgYDVR0fBIGiMIGfMDygOqA4hjZodHRwOi8vY3JsLnN5c3RlbXRlc3QxOS50cnVzdDI0MDguY29tL3N5c3RlbXRlc3QxOS5jcmwwX6BdoFukWTBXMQswCQYDVQQGEwJESzESMBAGA1UECgwJVFJVU1QyNDA4MSQwIgYDVQQDDBtUUlVTVDI0MDggU3lzdGVtdGVzdCBYSVggQ0ExDjAMBgNVBAMMBUNSTDYyMB8GA1UdIwQYMBaAFMwCVQzkgXSvIFTVERRXnJFSOH+gMB0GA1UdDgQWBBReXoe6mR11zHQv0ijlArnWLWd+2zAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQB282klteVINHqXZstuEV10hfn/4C2q/XcjFFlgayapYXcL6p+5Znw49fldmRKGvQ0nvjAIQD3soQNK3VBgnV7pL+KdmpyCQVv59WDjSNFeMbxwE1V5O3MDHw4S4DKivz1EDPgdZNPkgGOZQAA96ZmHsO4tq8n+TrNEDMkpHzcEQz9Ngu/H8/YYjRm8Dk+ffN7U2btu/XOXr5xhX3RCXhgoGuNY74Q7BsETO5ErIRKgtpX01iwwjs/HGKA50GZJnWeum1ssNXx2aT83hTGu96m1YvX3LnLPkOXsA1ocwv0USwadblrWlxDbULluC8THO7MpX+/uhLptwFXWgZv/Pr5k</ds:X509Certificate>
						</ds:X509Data>
					</ds:KeyInfo>
				</ds:Signature>
			</saml:Assertion>
		</Security>
		<Header xmlns="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd">
			<SecurityLevel>3</SecurityLevel>
			<TimeOut/>
			<Linking>
				<MessageID>-13392718-647611213</MessageID>
			</Linking>
			<RequireNonRepudiationReceipt>no</RequireNonRepudiationReceipt>
		</Header>
		<HsuidHeader xmlns="http://www.nsi.dk/hsuid/2016/08/hsuid-1.1.xsd">
			<Assertion IssueInstant="2018-04-23T00:20:13Z" id="HSUID">
				<Issuer>Epic</Issuer>
				<AttributeStatement id="HSUIDdata">
					<Attribute Name="nsi:UserType">
						<AttributeValue>HealthcareProfessional</AttributeValue>
					</Attribute>					
					<Attribute Name="nsi:SystemOwnerName">
						<AttributeValue/>
					</Attribute>
					<Attribute Name="nsi:SystemName">
						<AttributeValue>Epic</AttributeValue>
					</Attribute>
					<Attribute Name="nsi:SystemVersion">
						<AttributeValue>85.0</AttributeValue>
					</Attribute>
					<Attribute Name="nsi:OrgResponsibleName">
						<AttributeValue/>
					</Attribute>
					<Attribute Name="nsi:OrgUsingID" NameFormat="nsi:sorcode">
						<AttributeValue>6111000016004</AttributeValue>
					</Attribute>
				</AttributeStatement>
			</Assertion>
		</HsuidHeader>
	</s:Header>
	<s:Body>
		<ProvideAndRegisterDocumentSetRequest xmlns="urn:ihe:iti:xds-b:2007">
			<ns6:SubmitObjectsRequest ns6:id="000096fa-46b6-11e8-a6ea-460231621f93" xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0">
				<ns4:RegistryObjectList xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0">
					<RegistryPackage id="000099d4-46b6-11e8-a6ea-460231621f93">
						<Classification classificationScheme="urn:uuid:a7058bb9-b4e4-4307-ba5b-e3f0ab85e12d" classifiedObject="000099d4-46b6-11e8-a6ea-460231621f93">
							<Slot name="authorInstitution">
								<ValueList>
									<Value>Region Hovedstaden^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^6111000016004</Value>
								</ValueList>
							</Slot>
						</Classification>
					</RegistryPackage>
					<Association/>
					<ExtrinsicObject id="urn:uuid:000098ee-46b6-11e8-a6ea-460231621f93" mimeType="text/xml" objectType="urn:uuid:7edca82f-054d-47f2-a032-9b2a5b5186c1"/>
					<ClassificationNode code="urn:uuid:ab9b591b-83ab-4d03-8f5d-f93b1fb92e85"/>
				</ns4:RegistryObjectList>
			</ns6:SubmitObjectsRequest>
			<Document id="Patient-with-CPR-number-identification.xml">
				<xop:Include href="cid:http://tempuri.org/1/636600396142016797" xmlns:xop="http://www.w3.org/2004/08/xop/include"/>
			</Document>
		</ProvideAndRegisterDocumentSetRequest>
	</s:Body>
</s:Envelope>
```

Here is our CDA. 
It is an older version of the document that we don’t expect to pass schema/schematron, but are just trying to make sure the communication up to the schema/schematron validation is working.

```xml
<ClinicalDocument xmlns="urn:hl7-org:v3" classCode="DOCCLIN" moodCode="EVN">
	<realmCode code="DK"></realmCode>
	<typeId extension="POCD_HD000040" root="2.16.840.1.113883.1.3"></typeId>
	<templateId root="1.2.208.176.7.1.10.71"></templateId>
	<templateId root="2.16.840.1.113883.10.12.2"></templateId>
	<templateId root="2.16.840.1.113883.10.12.1"></templateId>
	<id extension="BB7D5882-472E-11E8-80C5-0050569C0201" root="9ce66a32-4335-11e8-80c5-0050569c0201"></id>
	<code code="34133-9" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Summary of episode note"></code>
	<effectiveTime value="20180423214427+0200"></effectiveTime>
	<confidentialityCode code="N" codeSystem="2.16.840.1.113883.5.25"></confidentialityCode>
	<setId assigningAuthorityName="EPC" root="9ce66a32-4335-11e8-80c5-0050569c0201"></setId>
	<versionNumber value="4"></versionNumber>
	<recordTarget>
		<templateId root="1.2.208.176.7.1.10.101"></templateId>
		<templateId root="2.16.840.1.113883.10.12.101"></templateId>
		<patientRole classCode="PAT">
			<templateId root="1.2.208.176.7.1.10.107"></templateId>
			<id extension="45" root="ECPR"></id>
			<addr>
				<streetAddressLine>422 Bard St</streetAddressLine>
				<streetAddressLine>Apt 10</streetAddressLine>
				<postalCode>56646</postalCode>
				<city>Madison</city>
				<country>5100</country>
				<useablePeriod>
					<low value="19800101"></low>
					<high value="20000101"></high>
				</useablePeriod>
			</addr>
			<addr>
				<streetAddressLine nullFlavor="UNK"></streetAddressLine>
				<postalCode nullFlavor="UNK"></postalCode>
				<city nullFlavor="UNK"></city>
				<country>5100</country>
			</addr>
			<patient classCode="PSN">
				<name>
					<family>Wood</family>
					<given>Bolly</given>
					<given>J</given>
					<prefix>Dr</prefix>
				</name>
				<administrativeGenderCode code="M" codeSystem="2.16.840.1.113883.5.1"></administrativeGenderCode>
			</patient>
		</patientRole>
	</recordTarget>
	<author typeCode="AUT">
		<templateId root="1.2.208.176.7.1.10.102"></templateId>
		<templateId root="2.16.840.1.113883.10.12.102"></templateId>
		<time value="20180423214427+0200"></time>
		<assignedAuthor classCode="ASSIGNED">
			<id nullFlavor="NI"></id>
			<representedOrganization classCode="ORG" determinerCode="INSTANCE">
				<id extension="6111000016004" root="1.2.208.176.1.1" assigningAuthorityName="SOR"></id>
			</representedOrganization>
		</assignedAuthor>
	</author>
	<custodian typeCode="CST">
		<templateId root="1.2.208.176.7.1.10.103"></templateId>
		<templateId root="2.16.840.1.113883.10.12.104"></templateId>
		<assignedCustodian classCode="ASSIGNED">
			<representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
				<id extension="29190623" root="2.16.840.1.113883.2.24.1.1" assigningAuthorityName="Erhvervs- og Selskabsstyrelsen"></id>
			</representedCustodianOrganization>
		</assignedCustodian>
	</custodian>
	<component contextConductionInd="true">
		<structuredBody>
			<component>
				<section>
					<templateId root="1.2.208.176.7.1.10.95"></templateId>
					<templateId root="2.16.840.1.113883.10.12.201"></templateId>
					<entry typeCode="COMP">
						<act classCode="PCPR" moodCode="EVN">
							<templateId root="1.2.208.176.7.1.10.80"></templateId>
							<templateId root="2.16.840.1.113883.10.12.301"></templateId>
							<id extension="88E17454-1D9D-11E8-86F0-0050568B7415" root="1.2.208.176.7.1.2.1"></id>
							<code nullFlavor="NA"></code>
							<effectiveTime>
								<low value="20010114000000+0100"></low>
								<high value="20020114000000+0100"></high>
							</effectiveTime>
							<entryRelationship typeCode="RSON">
								<act classCode="PCPR" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.51"></templateId>
									<templateId root="2.16.840.1.113883.10.12.301"></templateId>
									<code nullFlavor="NA"></code>
									<effectiveTime value="20010114000000+0100"></effectiveTime>
									<participant typeCode="REF">
										<templateId root="1.2.208.176.7.1.10.52"></templateId>
										<templateId root="2.16.840.1.113883.10.12.321"></templateId>
										<participantRole classCode="ROL">
											<scopingEntity classCode="ORG">
												<id extension="referralOrgId" root="1.2.208.176.1.1" assigningAuthorityName="SOR"></id>
											</scopingEntity>
										</participantRole>
									</participant>
									<entryRelationship typeCode="RSON">
										<act classCode="REG" moodCode="EVN">
											<templateId root="1.2.208.176.7.1.10.55"></templateId>
											<templateId root="2.16.840.1.113883.10.12.301"></templateId>
											<code code="DK076A" codeSystem="1.2.208.176.2.4"></code>
											<entryRelationship typeCode="COMP">
												<act classCode="REG" moodCode="EVN">
													<templateId root="1.2.208.176.7.1.10.5"></templateId>
													<templateId root="2.16.840.1.113883.10.12.301"></templateId>
													<code code="DR52" codeSystem="1.2.208.176.2.4"></code>
												</act>
											</entryRelationship>
											<entryRelationship typeCode="COMP">
												<act classCode="REG" moodCode="EVN">
													<templateId root="1.2.208.176.7.1.10.5"></templateId>
													<templateId root="2.16.840.1.113883.10.12.301"></templateId>
													<code code="DR07" codeSystem="1.2.208.176.2.4"></code>
												</act>
											</entryRelationship>
										</act>
									</entryRelationship>
									<entryRelationship typeCode="COMP">
										<act classCode="REG" moodCode="EVN">
											<templateId root="1.2.208.176.7.1.10.53"></templateId>
											<templateId root="2.16.840.1.113883.10.12.301"></templateId>
											<code codeSystem="1.2.208.176.2.4" nullFlavor="UNK"></code>
										</act>
									</entryRelationship>
									<entryRelationship typeCode="COMP">
										<act classCode="REG" moodCode="EVN">
											<templateId root="1.2.208.176.7.1.10.54"></templateId>
											<templateId root="2.16.840.1.113883.10.12.301"></templateId>
											<code codeSystem="1.2.208.176.2.4" nullFlavor="UNK"></code>
										</act>
									</entryRelationship>
								</act>
							</entryRelationship>
							<entryRelationship typeCode="COMP">
								<act classCode="REG" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.81"></templateId>
									<templateId root="2.16.840.1.113883.10.12.301"></templateId>
									<code code="ALDA20" codeSystem="1.2.208.176.2.4"></code>
								</act>
							</entryRelationship>
							<entryRelationship typeCode="COMP">
								<act classCode="REG" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.82"></templateId>
									<templateId root="2.16.840.1.113883.10.12.301"></templateId>
									<id extension="88E22254-1D9D-11E8-86F0-0050568B7415" root="1.2.208.176.7.1.2.1"></id>
									<code code="marker1SKS" codeSystem="1.2.208.176.2.4"></code>
									<effectiveTime value="20010114024640+0100"></effectiveTime>
								</act>
							</entryRelationship>
							<entryRelationship typeCode="COMP">
								<act classCode="REG" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.82"></templateId>
									<templateId root="2.16.840.1.113883.10.12.301"></templateId>
									<id extension="88E17454-1D9D-11E8-86F0-0050568B7222" root="1.2.208.176.7.1.2.1"></id>
									<code code="marker2SKS" codeSystem="1.2.208.176.2.4"></code>
									<effectiveTime value="20010114030320+0100"></effectiveTime>
								</act>
							</entryRelationship>
							<entryRelationship typeCode="COMP">
								<act classCode="REG" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.83"></templateId>
									<templateId root="2.16.840.1.113883.10.12.301"></templateId>
									<code code="ALAA03" codeSystem="1.2.208.176.2.4"></code>
									<reference typeCode="REFR">
										<templateId root="1.2.208.176.7.1.10.69"></templateId>
										<templateId root="2.16.840.1.113883.10.12.324"></templateId>
										<externalAct classCode="PCPR" moodCode="EVN">
											<templateId root="1.2.208.176.7.1.10.65"></templateId>
											<templateId root="2.16.840.1.113883.10.12.325"></templateId>
											<id extension="88E17454-1D9D-11E8-86F0-0050568B7415" root="1.2.208.176.7.1.2.1"></id>
										</externalAct>
									</reference>
								</act>
							</entryRelationship>
							<entryRelationship typeCode="COMP">
								<observation classCode="OBS" moodCode="EVN">
									<templateId root="1.2.208.176.7.1.10.105"></templateId>
									<templateId root="2.16.840.1.113883.10.12.303"></templateId>
									<code codeSystem="1.2.208.176.2.4" nullFlavor="UNK"></code>
								</observation>
							</entryRelationship>
						</act>
					</entry>
				</section>
			</component>
		</structuredBody>
	</component>
</ClinicalDocument>
```

**Comment by VassKi** [comment] 2018-04-28 04:56
Any ideas on this error we are getting?

**Comment by TueCN** [comment] 2018-05-01 11:15
I think the problem is caused by what is described on #102 - namely that you have entered SOR id `6111000016004`  in the authorInstitution slot. 
```XML
<Slot name="authorInstitution">
    <ValueList>
        <Value>Region Hovedstaden^^^^^&amp;1.2.208.176.1.1&amp;ISO^^^^6111000016004</Value>
    </ValueList>
</Slot>
```

Currently the service expects a CVR number in that slot and tries to parse whatever is entered as a integer because CVR numbers fit in the Java Integer data type, but  the number 6111000016004 does not.

Until #102 is resolved, you can work around this issue by entering the CVR number that you have already entered in custodian: `29190623`
```XM
<custodian typeCode="CST">
	<templateId root="1.2.208.176.7.1.10.103"></templateId>
	<templateId root="2.16.840.1.113883.10.12.104"></templateId>
	<assignedCustodian classCode="ASSIGNED">
		<representedCustodianOrganization classCode="ORG" determinerCode="INSTANCE">
			<id extension="29190623" root="2.16.840.1.113883.2.24.1.1" assigningAuthorityName="Erhvervs- og Selskabsstyrelsen"></id>
		</representedCustodianOrganization>
	</assignedCustodian>
</custodian>
```

The value `29190623` should just replace the value `6111000016004` - nothing else needs to be changed in the Value element

**Comment by jonigkeit** [comment] 2018-05-09 09:12
@VassKi can you close this issue now that #102 is created for the actual fix?

**Closed** 2018-05-09 14:16 UTC
Labels: bug, duplicate
