### ISSUE TITLE
LPR3 rule 5.108: is the diag.foedbarn.doed is missing in the validation?

### ISSUE THREAD

**Issue by clausheinecke** [scandihealth/lpr3-docs#249] opened 2018-12-05 11:34 UTC
When we report a stillborn child we get error 5.108 saying that we have not registered a valid diagnosis from the table diagn.doed.
But the diagnosis DP950 is in the diag.foedbarn.doed which should be a valid diagnosis for a stillborn child and should be reported as a Kontakttype DØD and priority=Akut.
See text in the LPR3 vejledning: Kontakttypen for fødselskontakten ved dødfødsel er ’død’. Aktionsdiagnosen er DP950 ’Dødfødt barn’. Aktionsdiagnosen er trigger for resultatindberetningen ’fødselsindberetning barn’.

**Comment by TueCN** [comment] 2018-12-06 19:03
Rule 5.108 seems to be implemented correctly according to the spec: 
![image](https://user-images.githubusercontent.com/14910711/49605328-73e82280-f990-11e8-8df8-47dada8c1d19.png)

The problem is that you are reporting an encounter with a type code in `admin.konttype.doed`, this triggers validation of rule 5.108, which checks that the aktionsdiagnose code is in `diag.dod`, which `DP950` is not. Thus it produces a validation error.

I think there is a problem with either the way rule 5.108 as is defined in [Logisk datamodel og indberetningsregler - Bilag 1 (PDF)](https://sundhedsdatastyrelsen.dk/-/media/sds/filer/rammer-og-retningslinjer/patientregistrering/indberetning-til-lpr3/vejledning-lpr3-bilag-1-model-og-indberetningsregler.pdf?la=da) or the fact that the SKS codes in `diag.foedbarn.doed` are not also in `diag.dod`.

I will raise the issue with SDS.

**Comment by smunck** [comment] 2018-12-07 08:56
SDS will update the code list [diag.dod] in SKS to contain aktionsdiagnose DP950 (dødfødt). The update will be part of the ordinary SKS-update next week (between 10-14 dec).

**Comment by clausheinecke** [comment] 2018-12-10 12:16
Hvad er nu næste skridt? Du har assigned problemet til mig – og hvad så??
/Claus
Med venlig hilsen
Claus Heinecke
Systemforvalter LPR
IT Systemforvaltning
Koncern IT

Mobil: +45 24 98 28 58
Mail: cbhi@regionsjaelland.dk<mailto:cbhi@regionsjaelland.dk>
Jabber: 75357@regionsjaelland.dk<mailto:75357@regionsjaelland.dk>
Nørregade 54, 4100 Ringsted
www.regionsjaelland.dk<http://www.regionsjaelland.dk/>
[Region Sjælland - vi er til for dig]<http://intra.regionsjaelland.dk/RegionenPåTværs/Viertilfordig>



Fra: Tue Carr Nørgård [mailto:notifications@github.com]
Sendt: 10. december 2018 13:07
Til: scandihealth/lpr3-docs <lpr3-docs@noreply.github.com>
Cc: Claus Bo Heinecke <cbhi@regionsjaelland.dk>; Assign <assign@noreply.github.com>
Emne: Re: [scandihealth/lpr3-docs] LPR3 rule 5.108: is the diag.foedbarn.doed is missing in the validation? (#249)


Assigned #249<https://github.com/scandihealth/lpr3-docs/issues/249> to @clausheinecke<https://github.com/clausheinecke>.

**Comment by TueCN** [comment] 2018-12-10 12:34
@clausheinecke next step is to wait for the SKS code lists to be updated as stated by https://github.com/scandihealth/lpr3-docs/issues/249#issuecomment-445165729

When the list has been updated, you should no longer see a validation error from rule 5.108

**Comment by Julie-Marie** [comment] 2018-12-18 09:10
This is tested and passed. Thank you

**Closed** 2018-12-18 09:50 UTC
Labels: question
